### ISSUE TITLE
Unable to select v2 of APIM 

### ISSUE THREAD

**Issue by drovani** [stephaneey/azure-apim-extension#23] opened 2018-11-12 20:01 UTC
When attempting to changing the version of the API Management task (regardless of which task is chosen), there is no ability to select a version other than "1.*".

![image](https://user-images.githubusercontent.com/898478/48372079-160f3600-e683-11e8-9dd4-3a127e2dd41a.png)

We've already tried to uninstall and reinstall the extension, but to no avail. This is for Azure DevOps; I don't have the ability to test in TFS on-prem.

**Comment by stephaneey** [comment] 2018-11-14 07:47
Hi,

There must be something wrong with your tenant as it should automatically update the extension. As you're the only one reporting this, I guess it is an isolated issue. You should ask MS support as the update process is a behind the scenes thing.

Best regards

**Comment by drovani** [comment] 2018-11-14 19:29
This is happening across multiple tenants, and even with a freshly created Azure DevOps account - just to be sure it wasn't something with configuration.

Is there a setting somewhere that may prohibit Version 2 from being displayed or selectable? Perhaps a dependency in Azure DevOps that v2 requires?

A lot of the features and problems we've been running into while attempting to use v1 look like they are solved in v2. Any assistance you can provide would be greatly appreciated.

**Comment by lurumad** [comment] 2018-11-16 09:35
Happen the same to me,

![image](https://user-images.githubusercontent.com/1729519/48613091-13665680-e98b-11e8-8e91-ca7627c3bb38.png)

I'm going to see what's happening. 

Maybe it's related to the new Azure Dev Ops. I've had to change the category to install in new Azure Dev Ops:

![image](https://user-images.githubusercontent.com/1729519/48613179-4e688a00-e98b-11e8-9b41-ccdeda787597.png)

```json
"categories": [
    "Azure Pipelines"
  ],
```

Regards!

**Comment by stephaneey** [comment] 2018-11-16 09:40
Crazy, they basically made a breaking change! I'm going to republish the extension with this new category...plus I cannot reproduce this on my own tenant

**Comment by lurumad** [comment] 2018-11-16 09:50
I can reproduce in my subscription, I can't select versions from each tasks so maybe they made a breaking change also in new Azure Dev Ops?

Regards!

**Comment by stephaneey** [comment] 2018-11-16 09:55
Well, I've just republished the extension with the right category "Azure Pipelines", however, on my tenant I have no issue...For sure, they made breaking changes since I haven't updated the extension plus it's even not consistent given that I cannot reproduce the problem on my side.

**Comment by stephaneey** [comment] 2018-11-16 09:57
Now that I have repackaged it using the last version of tfx-cli and that it didn't complain about anything, maybe it will work. Could you retry in an hour or so?

Thanks

**Comment by stephaneey** [comment] 2018-11-16 10:11
Ok I can also reproduce the issue on a fresh new tenant...what a heck! I'll have a look at it!

**Comment by stephaneey** [comment] 2018-11-18 13:42
Hey guys,

Some news: for me, it is clearly an Azure DevOps bug. I'm packaging the extension exactly as it should when having multiple versions of a task. If I only keep V2, it works on a fresh new tenant but I don't want to do that and take the risk to impact existing pipelines. I'm in touch with MS to see how to get this fixed...

**Comment by stephaneey** [comment] 2018-11-21 20:39
Hello,

Just to keep you posted on the latest things. Microsoft found the root cause and they should push a fix on Monday but given time zones, you should expect it fixed by Tuesday where I'll push a dummy update of the extension to make sure the MS fix gets into play.

Best Regards

**Comment by DibranMulder** [comment] 2018-11-22 07:59
Do you have any github issue where you can relate to? Just curious...

**Comment by stephaneey** [comment] 2018-11-27 11:01
Hello,

MS fixed the problem at their level and my test tenant was automatically updated so I can select V2 of tasks, so this should be fixed for you as well.

Best Regards

**Closed by stephaneey** 2018-11-27 11:01 UTC

**Comment by lurumad** [comment] 2018-11-27 11:04
Good news @stephaneey I'm going to talk with my customers!

Thanks!

**Comment by drovani** [comment] 2018-11-28 14:20
I can confirm that it is now working as expected on my tenants. Thank you for looking into this.
