### ISSUE TITLE
ERROR Create or update versioned API: You cannot call a method on a null-valued expression

### ISSUE THREAD

**Issue by CGascon86** [stephaneey/azure-apim-extension#58] opened 2019-08-12 13:00 UTC
I'm trying to publish an API into API Management using the Task  called 'API Management - Create or update versioned API' and it always return this error:
       "You cannot call a method on a null-valued expression"

What's the problem? I've fill all the fields of the task :(

Thank's :)
Regards

**Comment by thdotnet** [comment] 2019-09-28 05:24
I am facing the same problem, do you know how to solve it?

**Comment by CGascon86** [comment] 2019-10-16 11:01
No... I'm still having the problem :(

**Comment by stephaneey** [comment] 2020-02-16 18:50
Hello,

Since you don't give any context (Azure DevOps Server or Services, etc.) and since I cannot reproduce this, I'll simply close the issue. Feel free to open a new one **with more details** about the problem you are facing.

Thanks
Best Regards

**Closed by stephaneey** 2020-02-16 18:50 UTC
