### ISSUE TITLE
Create or Update Versioned API 3.3.0 does not set serviceUrl from an Open API 3.0.1 JSON file

### ISSUE THREAD

**Issue by cpdohert** [stephaneey/azure-apim-extension#48] opened 2019-04-30 16:38 UTC
This is the first chunk of my OpenAPI v3.0.1 JSON file:

```
{
    "openapi": "3.0.1",
    "info": {
        "title": "XXXcustomerXXX",
        "version": "v1"
    },
    "servers": [
        {
            "url": "https://my-service.azurewebsites.net/api/v1"
        }
    ],
    "paths": {
        "/bookable-providers/{id}": {
            "get": {
                "summary": "GetBookableProvider",
                "description": "Get a bookable-provider by Id.",
                "operationId": "bookable-providers",
[...]
```

If I import this to my APIM resource within the Azure Portal (APIs > Add API > OpenAPI v3) or by right-clicking the three dots and importing the file over top of the pre-existing API, everything works as I expect.

Using v3.3.0 of the **Create or Update Versioned API** task to deploy this same file does not populate the serviceUrl field (in the Azure Portal, the API > Settings > Web service URL field).

The task succeeds but the serviceUrl field is null:

```2019-04-30T16:21:31.6665514Z Importing swagger https://management.azure.com/subscriptions/4169a752-61b4-4fc2-9e79-5bde32e02130/resourceGroups/XXXrgXXX/providers/Microsoft.ApiManagement/service/XXXapimXXX/apis/XXXcustomerXXX?import=true&api-version=2017-03-01 spec is v3 format is json
2019-04-30T16:21:31.6683401Z API Body is <redacted>
2019-04-30T16:21:31.6706530Z ##[debug]PUT https://management.azure.com/subscriptions/4169a752-61b4-4fc2-9e79-5bde32e02130/resourceGroups/XXXrgXXX/providers/Microsoft.ApiManagement/service/XXXapimXXX/apis/XXXcustomerXXX?import=true&api-version=2017-03-01 with -1-byte payload
2019-04-30T16:21:34.0866806Z ##[debug]received 1423-byte response of content type application/json; charset=utf-8
2019-04-30T16:21:34.1140791Z StatusCode        : 200
2019-04-30T16:21:34.1141513Z StatusDescription : OK
2019-04-30T16:21:34.1142145Z Content           : {
2019-04-30T16:21:34.1218431Z                       "id": "/subscriptions/4169a752-61b4-4fc2-9e79-5bde32e02130/resourceGroups/XXXrg
2019-04-30T16:21:34.1218976Z                     XXX/providers/Microsoft.ApiManagement/service/XXXapimXXX/apis/XXXcustomerXXX
2019-04-30T16:21:34.1219966Z                     iq",
2019-04-30T16:21:34.1220660Z                       "type": "Microsoft.ApiManagement/service/apis",
2019-04-30T16:21:34.1221368Z                       "name": "XXXcustomerXXX",
2019-04-30T16:21:34.1221943Z                       "properties": {
2019-04-30T16:21:34.1222574Z                         "displayName": "XXXcustomerXXX",
2019-04-30T16:21:34.1223590Z                         "apiRevision": "1",
2019-04-30T16:21:34.1224323Z                         "description": null,
***
2019-04-30T16:21:34.1224920Z                         "serviceUrl": null,
***
2019-04-30T16:21:34.1225951Z                         "path": "XXXcustomerXXX",
2019-04-30T16:21:34.1226685Z                         "protocols": [
2019-04-30T16:21:34.1227349Z                           "https"
2019-04-30T16:21:34.1228042Z                         ],
```

**Comment by cpdohert** [comment] 2019-04-30 17:15
Additional information: this happens with all three Microsoft API versions exposed by the task (2017-03-01, 2018-01-01, 2018-06-01-preview)

**Comment by riccardobecker** [comment] 2019-05-13 09:45
Do you already have an update on this issue? I am experiencing the same issue!

**Comment by stephaneey** [comment] 2019-05-13 10:46
Hi,

Sorry for my late answer, I was in holidays... I'll have a look at it this week. 

Best Regards

**Comment by jetedrow** [comment] 2019-05-21 18:28
I am bumping this issue - It is affecting me in my deployments also.

**Comment by stephaneey** [comment] 2019-06-01 09:02
Hello,

Do you still have the issue? I've tried with both Swagger & YAML inputs and it works fine. I have my resulting URL correctly filled in. I also tried to either deploy from scratch, either deploy a new version only and I always have the service URL correctly set.

Please let me know or provide me with your swagger.

Thanks

**Comment by stephaneey** [comment] 2019-06-04 07:01
Hello,

Feel free to reopen the issue but since I'm not able to reproduce and since I do not have any news from your end, I'll just close it.

Best Regards

**Closed by stephaneey** 2019-06-04 07:01 UTC

**Comment by jmereaux** [comment] 2019-06-05 09:14
Hi, I am having the exact same issue.
Here is the basic swagger I'm using

```
{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Test API documentation",
    "description": "The API endpoints offered by the Test application",
    "termsOfService": "None",
    "contact": {
      "name": "Johan Mereaux",
      "url": "http://www.jm.com",
      "email": "johan.mereaux@gmail.com"
    },
    "license": {
      "name": "JM 2019",
      "url": "http://www.jm.com"
    }
  },
  "host": "testjm.azurewebsites.net",
  "paths": {
    "/api/v1.0/Users/me": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Récupère les informations de l'utilisateur connecté.",
        "operationId": "ApiV1.0UsersMeGet",
        "consumes": [],
        "produces": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  }
}
```

**Comment by akamud** [comment] 2020-04-14 14:25
I'm still having this issue using Open API 3.0.1.

**Comment by akamud** [comment] 2020-04-14 14:28
This could be set in the request using: `properties.serviceUrl` and could be an extra parameter in the Task.
